# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8652a82da549f058b978cfa836e9887d69bd7324ec5cf3637a411c142547bd90555577f631f0eacd509bea6cb6c74a66f140a793fb47b11efdc5ab862b064f8f

test:
  secret_key_base: 7a7388e5bbd8592e42e4657d36eb6a063e6f26a3d30a17110b7c61997b88621217013683b1217cdbeebf33f3933898f3251be264a48aeab14ff15ef08342ee3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
